### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#320]
I've just noticed that the "Contribute" link on http://gpiozero.readthedocs.io/en/latest/index.html#development gives a 404 error.

**Comment by bennuttall** [comment]
@waveform80 is that a case of changing the link in README to an absolute link, or can it be fixed otherwise?

**Comment by waveform80** [comment]
Good question - I'll have a play when I get a sec (probably not too hard)

**Comment by waveform80** [comment]
Yeah, an absolute link fixes it. I'd kinda like to include "Contributing" as a chapter in the docs, though (actually I think it *has* to be a chapter or at least a sub-section if you link to it from elsewhere in the docs).

I'll see what I can do (although I suspect it's going to be a horrid hack because GitHub's using file-like addressing, i.e. CONTRIBUTING.md while sphinx will assume URLs shouldn't be modified - i.e. it'll try and link to something like CONTRIBUTING.md but it should be CONTRIBUTING.html - anyway, I'll come up with some sort of workaround).
