### ISSUE TITLE
code warning for ADC's (MCP 3208, MCP 3304)

### ISSUE THREAD

**Issue by pcopa** [RPi-Distro/python-gpiozero#409]
FYI, I've flashed a new SD card with the latest versions and even though everything is working fine, I'm getting the following warning when starting the code:

![image](https://cloud.githubusercontent.com/assets/15312957/17945995/5164cc4e-6a14-11e6-8bdb-db313d146836.png)

(Why is my picture not showing?)

**Comment by pcopa** [comment]
Sarting over new. Cut and past not working across platforms for me.

FYI, I've flashed a new SD card with the latest versions and even though everything is working fine, I'm getting the following warning when starting the code:

"Warning (from warnings module):
  File "/usr/lib/python2.7/dist-packages/gpiozero/spi.py", line 416
    'software (error was: %s)' % str(e)))
SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)"

**Comment by bennuttall** [comment]
Hi @pcopa 

> (Why is my picture not showing?)

I don't know why, but looking at the URL of the image, it's a 1px x 1px image. I'm guessing that's not what you uploaded so it must have got lost somewhere in the tubes.

> SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)"

This is the expected behaviour in your case.

Since the last release, we added a software fallback for SPI. If you have SPI enabled in raspi-config AND you have the spidev Python module installed, then gpiozero uses hardware SPI. If not, it uses a pure Python implementation (you can even change the pins used to any set of GPIOs). See http://gpiozero.readthedocs.io/en/v1.2.0/api_spi.html

The warning you're seeing is a [warning](https://docs.python.org/3/tutorial/errors.html), not an [exception](https://docs.python.org/3/library/warnings.html). You can [disable warnings](http://stackoverflow.com/questions/14463277/how-to-disable-python-warnings).

**Comment by pcopa** [comment]
Thanks for the explanation. will close the comment.
