### ISSUE TITLE
Strange issue with LED.on(), it just blinks

### ISSUE THREAD

**Issue by DrCroubie** [RPi-Distro/python-gpiozero#510]
Like the title says.
Brand new Pi 3.
Brand new install of official Noobs Lite.
LEDs connected to Pi via a little open-drain breakout board that I made (just gpio to gate and drain to LED from 12V)
Boot up (set to autologin to default 'pi' account), type in 'python'.
Type in 'from gpiozero import LED'
Then 'LED(25).on()' and the LED just flashes on and goes off. I can type the same in again and it does the same, it's just going off straight away. I haven't hooked a scope up to it yet but it's got to be about 0.1s or less on-time.
LED(25).toggle() does the same thing.

Now here's the weird part.
If instead I type in 'LED(25).blink()', it happily stays on the full 1 second of the blink time, it doesn't go off straight away.

I've tried 'sudo python' and just logging in as root in case that fixes anything (I read in one of your comment something about pigpiod running as root), but no difference. Also, it's all the LEDs that I've tried. 14, 15, 18, 25 so far. Also, when I boot the pi on, LED(15) is just on. and the other three I've hooked up are off. once in python I can LED(15).off() then it behaves like the others. But I've disabled the uart raspi-config so it can't still be a resource conflict can it?

So code problem? Pi3 problem? Config.txt file has something wrong in it? Any suggestions? (I'm just about to go away for a few days over nye, but when I get back I'll try just doing it from the raw 'pigpio' library to see what that does).

**Comment by lurch** [comment]
It's a code problem. When you do `LED(25).on()` the python code in GpioZero creates an LED object on gpio 25, then calls its `on()` method, but because the newly-created object isn't being stored anywhere, it then gets garbage-collected, and in gpiozero when an object is garbage collected it gets 'switched off'.

So what you need to instead do is:
```
from gpiozero import LED
myled = LED(25)
myled.on()
```
and the LED will stay on, but as soon as you exit the python interpreter, it'll switch off again.

Have another look at [the examples](https://gpiozero.readthedocs.io/en/v1.3.1/recipes.html#led) and make sure you also read [this](https://gpiozero.readthedocs.io/en/v1.3.1/notes.html#keep-your-script-running).
