### ISSUE TITLE
Performance issues with pkg_resources

### ISSUE THREAD

**Issue by BuddhaOhneHals** [RPi-Distro/python-gpiozero#675]
I want to use your library in one of my projects with a Raspberry Pi Zero. Until now I used RPi.GPIO but your API seems just great. But one issue that bothers me is the duration when I'm importing the gpiozero module.
I use a freshly installed raspbian lite (`2018-06-27-raspbian-stretch-lite`) with the gpiozero package installed via `apt`. The import of gpiozero in the python shell needs 5 seconds or more.
```
$ python -c "from timeit import default_timer as t;s=t();import gpiozero;print(t()-s)"
5.40878105164
```
It seems like the import of the `pkg_resources` package in the `devices.py` file is responsible for this:
```
$ python -c "from timeit import default_timer as t;s=t();import pkg_resources;print(t()-s)"
4.59635186195
```
It would be really great and helpful if there's a possibility to skip the importing of the `pkg_resources` package.

**Comment by bennuttall** [comment]
My first impression is that surely the bottleneck isn't `pkg_resources` but just how big gpiozero is.

We've noticed long import delays, especially on Pi 1/Zero. It's purely because there are so many classes provided in the module's init file. We've considered moving imports out of here but that would change the way imports work: `from gpiozero import LED` would become `from gpiozero.outputs import LED`.

You can do this now, using the filenames the classes are in. Can you try `from gpiozero.output_devices import LED` (or similar - for the stuff you're importing - just [look at the files they're in](https://github.com/RPi-Distro/python-gpiozero/tree/master/gpiozero)) - and see if that makes it any faster?

**Comment by BuddhaOhneHals** [comment]
Unfortunately no differences:
```
$ python -c "from timeit import default_timer as t;s=t();from gpiozero.output_devices import LED;print(t()-s)"
4.41987299919
```

**Comment by BuddhaOhneHals** [comment]
It seems to be the usage of the `pkg_resources`-package.

I removed the import of the package from the `devices.py` file and replaced the body of `_default_pin_factory` with the following  two lines:
```
def _default_pin_factory(name=os.getenv('GPIOZERO_PIN_FACTORY', None)):
    from gpiozero.pins.rpigpio import RPiGPIOFactory
    return RPiGPIOFactory()
```
And now:
```
$ python -c "from timeit import default_timer as t;s=t();from gpiozero.output_devices import LED;print(t()-s)"
0.619349002838
```

**Comment by BuddhaOhneHals** [comment]
I see two possible solutions:

- Introduce a new optional env variable to provide a concrete factory class (`gpiozero.pins.rpigpio:RPiGPIOFactory`). If provided, skip the usage of `pkg_resources`. Instead, import the factory class with  the standard module `importlib`. Nothing else changed.
- Don't use the `pkg_resources` module at all. Instead try to import the factory class with the standard module `importlib`.

The first solution can be realized without much refactoring. I made a proof of concept: https://github.com/BuddhaOhneHals/python-gpiozero/pull/1/files

**Comment by waveform80** [comment]
First of all, thank you very much for a detailed and comprehensive bug report! I really enjoy seeing these, especially when they prove my assumptions wrong (as this one did). Unfortunately that's the good news; the bad news is there isn't much we can (or really want to) do about this. In a bit I'll get into the detail of this, but first let's deal with Ben's comments above:

> My first impression is that surely the bottleneck isn't pkg_resources but just how big gpiozero is.

Yup, that was my assumption (and what I told Ben when this first cropped up as a concern - I forget exactly when that was). In other words, don't blame Ben for that - it's my presumption he's repeating there.

> We've noticed long import delays, especially on Pi 1/Zero. It's purely because there are so many classes provided in the module's init file. We've considered moving imports out of here but that would change the way imports work: from gpiozero import LED would become from gpiozero.outputs import LED.

On the other hand, you *can* blame him for this: it doesn't work because of course the main `gpiozero/__init__.py` module (which will be implicitly executed by any import of gpiozero) imports everything else to ensure there's a flat namespace, so even `from gpiozero import LED` imports everything (even if it then discards it from the importing module's namespace). I *think* I told Ben that too, but if I did he's forgotten it ;)

Right, onto your detailed readings:

> It seems like the import of the pkg_resources package in the devices.py file is responsible for this:
> ...

Fascinating stuff! As mentioned above I'd always assumed that gpiozero's slow import time was down to our enormous class hierarchy and spread of modules (compared to things like RPi.GPIO). However, your measurements conclusively point to pkg_resources as a major portion of that. I've spent a little time this evening digging into the detail with a profile analyzer (runsnake for py2, and snakeviz for py3) and overall `pkg_resources` accounts for ~80% of the import time. That's a little less than your measurements suggest but that's because there's some overhead for python's builtins which is included regardless.

Looking at why pkg_resources is so slow, it turns out it's doing a fairly huge amount of work loading packages and comparing versions (which are quite complex to parse and compare). It could probably be sped up with a bit of caching, but I doubt that's a concern of upstream as it'll generally be a one-off cost which'll pale in comparison to most of the application's runtime.

Which brings me to your two solutions:

> * Don't use the pkg_resources module at all. Instead try to import the factory class with the standard module importlib.

I'll deal with the simple one first: this isn't going to happen. We use `pkg_resources` to provide the ability for third parties to include their own pin implementations with minimal pain, via the entry-points mechanism. At the moment I'm aware of two additional pin implementations that use this functionality, so we can't remove this without hurting them and frankly we don't want to because it's a widely understood mechanism that's easy for others to use.

> * Introduce a new optional env variable to provide a concrete factory class (gpiozero.pins.rpigpio:RPiGPIOFactory). If provided, skip the usage of pkg_resources. Instead, import the factory class with the standard module importlib. Nothing else changed.

This is a possibility ... but it duplicates functionality (`GPIOZERO_PIN_FACTORY` already provides this, albeit via `pkg_resources`), it's a lot more fiddly to use (ease of use is a pretty major thing for us), and ultimately it comes down to this: it's just to avoid a one-off cost at script start up. Is 5 seconds really going to be the vast majority of your script's runtime? If it is, then it's going to have a very short effect given that gpiozero attempts to reset pin states at termination. 

I *could* move the import of `pkg_resources` into `_default_pin_factory` and add special cases for the built-in drivers like `rpigpio` et al to avoid the import entirely (or add `GPIOZERO_PIN_FACTORY_CLASS` as you suggest), but that's adding complexity for something I'm not yet convinced is a problem. If someone can show me a use-case where the import time is genuinely a problem (and the use-case isn't a transient one-shot script; see pin reset above), then I'll consider it but I'm not there *yet*.

**Comment by BuddhaOhneHals** [comment]
Thank you for your detailed answer and your thoughts about the possible solutions.

I start with the use-case: I built a small jukebox for my daughter using a Pi Zero and some input and output devices for interaction. I put a lot of effort into decreasing the startup duration (using buildroot for example). My daughter would accept 4 or 5 seconds more (perhaps), but I wouldn't  ;)

At the moment I use RPi.GPIO, but I want to improve the scripts and GPIO Zero would be really handy (and the API is beautiful, btw.).

I understand your caution in changing the behavior of the importing mechanism and that you are trying to minimize the complexity. I will use my fork as long as I'm the only one bothered by this.

So, thank you again looking into this!

Btw: I didn't blame anybody for anything :D

**Comment by bennuttall** [comment]
Thanks for raising this - it's definitely an issue. From my point of view, if we can skip `pkg_resources` when pin factory is specified, that would be a good workaround. Just a matter of how complex the fix is how quickly we can implement it.

**Comment by BuddhaOhneHals** [comment]
That's great! Thanks a lot.

**Comment by lurch** [comment]
@waveform80 

> At the moment I'm aware of two additional pin implementations that use this functionality

Oh cool, I never knew that! Can you share what / who they are?

**Comment by cjw296** [comment]
Great to see this was done, anyone able to sanity check whether these numbers now look right for an original Pi board (the ones they gave to all PyCon attendees in, what, 2009?:

```
(energenie) chris@gozer:~/energenie $ pip freeze | grep gpio
gpiozero==1.5.1
(energenie) chris@gozer:~/energenie $ python -c "from timeit import default_timer as t;s=t();from gpiozero.output_devices import LED;print(t()-s)"
1.5013622678816319
```

If so, anything I can do to speed it up? Fast flash card? Should I just get a new Pi?

**Comment by lurch** [comment]
> in, what, 2009?

Seems unlikely, Raspberry Pi is now 8 years old :wink: https://www.raspberrypi.org/blog/raspberry-jams-celebrate-8th-birthday/

> Should I just get a new Pi?

I don't have time to dig out an older Pi, but on my Pi4B (which admittedly has its rootfs on a USB SSD rather than a microSD card) your second line above prints `0.140715122223` :slightly_smiling_face:

**Comment by bennuttall** [comment]
pip is incredibly slow, pi 1 is incredibly slow (700MHz single-core). We removed the pkg_resources bottleneck from gpiozero import so it's not a big problem now.

> If so, anything I can do to speed it up? Fast flash card? Should I just get a new Pi?

Faster card, new Pi, or be aware of the above and have some patience :)
