### ISSUE TITLE
Change Motor's "back" init arg to "reverse"

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#79]

**Comment by bennuttall** [comment]
Should the `backwards` method be called `reverse` too? Same would apply to the `Robot` interface.

**Comment by waveform80** [comment]
Good question. I'd suggest changing it to "backward" just to match the corresponding method name (so if people remember the method name they implicitly remember the parameter name too).

On a similar note, now we've got `values` in the base GPIODevice class, I'm pondering how to add something similar to Motor and then Robot. There's two ways of going about this:

1. Expose the underlying forward and backward objects so that people can tie things directly to `motor.forward_device.source` (or something similar).

2. Expose a `source` (and `values`) for Motor directly where, say, +1.0 means it's going forward full speed, and -1.0 means going backward full speed.

The latter appeals to me in some way, but then there's a question of what you do with a two motor robot class. After all, if Motor has values, shouldn't Robot? So, what does turning left equate to? Turning right? Going forward? Spinning round in circles? All of a sudden it's difficult to map to a single ... value ... huh ... compound values ... tuples. Of course, why didn't I think of that until I wrote all this out. Okay, never mind, I know where to go with this now.

**Comment by bennuttall** [comment]
>  I'd suggest changing it to "backward" just to match the corresponding method name

I'm proposing that they both be called `reverse`. Thoughts?

> Expose the underlying forward and backward objects so that people can tie things directly to `motor.forward_device.source` (or something similar).

Yes please!

> Expose a `source` (and `values`) for Motor directly where, say, +1.0 means it's going forward full speed, and -1.0 means going backward full speed.

Yes please!

I saw an example like this with an early Flotilla prototype. It used two slider pots to control the left and right motors respectively: high pot value = forwards; low pot value = backwards; mid point pot value = still. Very neat! Though requires mapping `1` to `forward(1)`; `0` to `backward(1)`; `0.5` to `stop()` and everything in between accordingly. Alternatively there are cases you'd use more or fewer pots...

**Comment by bennuttall** [comment]
**Decision: leave as `backward()`**

However, we should also update the init args of `Motor` to `forward` and `backward`.
