### ISSUE TITLE
Optional PWM interface to boards?

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#90]
I can create an instance of a `TrafficHat`, but then I have access only to `LED` objects, meaning I can't dim or pulse the LEDs.

How about adding a PWM option on init?

```python
th = TrafficHat(pwm=True)
```

Then the LEDs would be created as `PWMLED` objects.

**Comment by waveform80** [comment]
Nice!

**Comment by bennuttall** [comment]
Cool, I'll see what I can do!

**Comment by bennuttall** [comment]
Oh, you self-assigned. Feel free - otherwise I'll happily tackle it.

**Comment by waveform80** [comment]
Go for it if you've got the time - I'm probably going to be rather busy with HackMcr Jr tomorrow and Tuesday (might have some time in the evenings).

**Comment by bennuttall** [comment]
Ah, yes. Good luck with it!

**Comment by bennuttall** [comment]
Implemented in branch `fix-90`. Seems to work. Quite a handy option.

In `LEDBoard` I do it this way:

```python
def __init__(self, *pins, pwm=False):
    super(LEDBoard, self).__init__()
    LEDClass = PWMLED if pwm else LED
    self._leds = tuple(LEDClass(pin) for pin in pins)
```

And added it to other boards.

With `TrafficHat` I can set `th.lights.red.value = 0.5` but can't seem to set `th.lights.value = (1, 0.5, 0.1)`?

@waveform80 what do you think?

**Comment by waveform80** [comment]
Huh, that's weird - I'll look into it as a superficial glance at the code suggests that ought to work...

**Comment by waveform80** [comment]
Oh, one little problem - that syntax you've used in `LEDBoard.__init__` is Python 3 specific (in Python 2 you can't have anything by `**kwargs` after `*args` because Python 2 had no concept of keyword-only args). I'll tweak it so it's compatible with both but I'm afraid it's going to look a little ugly.

**Comment by waveform80** [comment]
Ahh ... I'm beginning to remember why I started avoiding the decorator syntax for properties. This is a [long-standing issue](http://bugs.python.org/issue14965) (although it's seen more as a feature by many on python-dev) with `super()`. There's two ways to work around it...

One: stick with decorator syntax and use the following body:

```python
@property
def value(self):
    return TrafficLightTUple(*super(TrafficLights, self).value)

@value.setter
def value(self, value):
    super(TrafficLights, self.__class__).value.fset(value)
```

Two: switch to method syntax. With this syntax you can just call the super-class' property methods directly (because they have different names):

```python
def _get_value(self):
    return TrafficLightTuple(*super(TrafficLights, self)._get_value())

def _set_value(self, value):
    super(TrafficLights, self)._set_value(value)

value = property(_get_value, _set_value)
```

I've gone with the first just to maintain consistency in the use of the decorator syntax.
